
- :group: austria
  :array:
#  - :interval: 450
#    :desc: austria_kargogel
#    :url: http://karkogel.it-wms.com/big_current4.jpg
  - :interval: 180
    :desc: austria_aflenz
    :url: http://www.aflenz-outdoorpark.at/webcam/webcam.jpg
#  # position changed, large amount of data
#  - :interval: 210
#    :desc: austria_blumental
#    :url: http://www.blumentalcam.at/cam_1.jpg
#    :coord:
#      :lat: 47.256649
#      :lon: 11.408386
#    :use_in_timelapse: true
  - :interval: 390
    :resize: true
    :desc: austria_silvretta1
    :url: http://www.silvretta-montafon.at/webcam/image1_text.jpg
  - :interval: 390
    :resize: true
    :desc: austria_silvretta2
    :url: http://www.silvretta-montafon.at/webcam/image2_text.jpg

  # TODO disable, unless new storage
  - :interval: 180
    :desc: austria_mondi
    :url: http://91.112.132.150/record/current.jpg
    :coord:
      :lat: 47.256649
      :lon: 11.408386
    :use_in_timelapse: true

#  - :interval: 150
#    :desc: innsbruck_lans
#    :url: http://live.tyrol.at/tyrolcams/lans/lans.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :interval: 120
#    :desc: obertauern
#    :url: http://www.snowwhite.at/obertauernwebcam/webcam01.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
  - :interval: 180
    :desc: saalfelden_hotel_Ritzenhof1
    :url: http://www.ritzenhof.at/webcam/cam1/cam1.jpg
    :resize: true
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 180
    :desc: saalfelden_hotel_Ritzenhof2
    :url: http://www.ritzenhof.at/webcam/cam2/cam2.jpg
    :resize: true
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 180
    :desc: austria_gasthof_geierwallihof
    :url: http://geierwallihof.at/MOBOTIX/test.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
#  # boring
#  - :interval: 320
#    :desc: austria_schruns
#    :url: http://schruns-tschagguns.at/kamera/kamera/aktuell.jpg
#    :resize: false
#    :coord:
#      :lat: 47.080048
#      :lon: 9.920596
#    :use_in_timelapse: false

  - :interval: 240
    :desc: austria_tschagguns
    :url: http://webcams.salmhofer.at/webcam/tschagguns.jpg
    :resize: false
    :coord:
      :lat: 47.080008
      :lon: 9.901684
    :use_in_timelapse: false

#  - :interval: 240
#    :desc: austria_bezaus
#    :url: http://www.hotelpostbezau.com/webcam/live/live.jpg
#    :resize: false
#    :coord:
#      :lat: 47.385427
#      :lon: 9.90251
#    :use_in_timelapse: false

  - :interval: 250
    :desc: austria_schruns_ferienhotel
    :url: http://www.ferienhotel.at/kamera/kamera/aktuell.jpg
    :resize: false
    :coord:
      :lat: 47.385427
      :lon: 9.90251
    :use_in_timelapse: false

  - :interval: 300
    :desc: austria_bad_gastein
    :url_schema:
      :url_schema: "http://panodata1.panomax.at/cams/23/%Y/%m/%d//%H-%M-00_default.jpg"
      :time_modulo: 600 # every 20 minutes
      :time_offset: 0 # 12 minutes
    :referer: "http://www.panomax.at/"
    :proxy: true
    :flags:
      :big_archive: true
    :resize: false
    :coord:
      :lat:
      :lon:
    :use_in_timelapse: false

  - :interval: 120
    :desc: austria_Kufsteinblick
    :url: http://www.webcam.kufnet.at/livebild/kufsteinblick/image.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 180
    :desc: austria_lienz
    :url: http://www.hochsteinhuette.at/images/stories/webcam/livebild.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

#  # quite low on photo quality
#  - :interval: 180
#    :resize: true
#    :jpg_quality_offset: -4
#    :desc: austria_loser1
#    :url: http://www.mentalworks.com/live/altaussee.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

  - :interval: 300
    :desc: austria_loser3
    :url: http://www.mentalworks.com/live/loser.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: austria_Luckneralm
    :url: http://www.lucknerhuette.at/webcam/lucknerhuette.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

#  - :interval: 300
#    :desc: austria_Neue_Regensburger
#    :url: http://www.regensburgerhuette.at/fileadmin/webcam/html/fileadmin/IPCamera/snapshot-wz.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
