---
- :group: world
  :array:
  - :resize: true
    :url: http://www.liveevent.se/webbkamera/tv4/goteborg/tv4_goteborg_1_1280.jpg
    :interval: 180
    :desc: sweden_goteborg
  - :url: http://www.gehammar.se/not001.jpg
    :interval: 450
    :desc: sweden_hjalmo
  - :resize: true
    :url: http://www.liveevent.se/webbkamera/ca-kalmar/ca_kalmar_1_1280.jpg
    :interval: 180
    :desc: sweden_kalmar
  - :resize: true
    :url: http://www.venjan.se/cam/kupan_cam.jpg
    :interval: 300
    :desc: sweden_kupan
  - :resize: true
    :url: http://livecam.mora.se/imageb.jpg
    :interval: 300
    :desc: sweden_vosalo
  - :resize: true
    :url: http://87.237.210.145/~checkpoi/webcam/klappen/webcam_10_1280.jpg
    :interval: 450
    :desc: sweden_klappen
  - :resize: true
    :url: http://www.hamrafjallet.se/kamera/webbkamror/topmega.jpg
    :interval: 600
    :desc: sweden_tandallen
  - :resize: true
    :url: http://www.liveevent.se/webbkamera/tv4/sundsvall/tv4_sundsvall_1_1280.jpg
    :interval: 450
    :desc: sweden_tvn4
  - :resize: true
    :url: http://dedi68.aname.net/~checkpoi/webcam/unostorn/webcam_6_1280.jpg
    :interval: 300
    :desc: sweden_unostorm
  - :resize: true
    :url: http://87.237.210.145/~checkpoi/webcam/visby_stora_torget/webcam_10_1280.jpg
    :interval: 300
    :desc: swedeb_visby
    :coord:
      # faked
      :lat: 45.085278
      :lon: 20.659444
    :use_in_timelapse: true
  - :interval: 600
    :desc: finland_koppola
    :url: http://85.157.217.2/-wvhttp-01-/GetStillImage
  - :interval: 450
    :desc: austria_kargogel
    :url: http://karkogel.it-wms.com/big_current4.jpg
  - :interval: 360
    :desc: austria_aflenz
    :url: http://www.aflenz-outdoorpark.at/webcam/webcam.jpg
  - :interval: 400
    :desc: austria_blumental
    :url: http://www.blumentalcam.at/cam_1.jpg
    :coord:
      :lat: 47.256649
      :lon: 11.408386
    :use_in_timelapse: true
  - :interval: 390
    :resize: true
    :desc: austria_silvretta1
    :url: http://www.silvretta-montafon.at/webcam/image1_text.jpg
  - :interval: 390
    :resize: true
    :desc: austria_silvretta2
    :url: http://www.silvretta-montafon.at/webcam/image2_text.jpg
  - :interval: 300
    :desc: austria_mondi
    :url: http://91.112.132.150/record/current.jpg
    :coord:
      :lat: 47.256649
      :lon: 11.408386
    :use_in_timelapse: true
  - :interval: 300
    :desc: antar_neumayeriT
    :url: http://www.awi.de/NM_WebCam/neumayerT.last.jpg
  - :interval: 300
    :desc: troyes
    :url: http://www.vision-environnement.com/webcams/Troyes2/image/webcam.jpg
  - :interval: 300
    :desc: antar_neumayerP
    :url: http://www.awi.de/NM_WebCam/neumayerP.last.jpg
  - :interval: 450
    :desc: antar_neumayer
    :url: http://www.awi.de/NM_WebCam/neumayer.last.jpg
  - :interval: 220
    :desc: de_mount1
    :url: http://cms.zugspitze.de/static/webcams/k02.jpg
  - :interval: 220
    :desc: de_mount2
    :url: http://cms.zugspitze.de/static/webcams/k04.jpg
    :coord:
      :lat: 45.866667
      :lon: 6.883333
    :use_in_timelapse: true
  - :interval: 300
    :desc: usa_san_francisco
    :url: http://wwc.instacam.com/instacamimg/SANFR/SANFR_l.jpg
    :coord:
      :lat: 37.7793
      :lon: -122.4192
    :use_in_timelapse: true
  - :interval: 360
    :desc: italy_mount1
    :url: http://www.ras.bz.it/img_webcams/scheibe/scheibe_P1.jpg
  - :interval: 360
    :desc: hahnenkoepfle
    :url: http://tramino.s3.amazonaws.com/s/das-hoechste/webcams/ifen-hahnenkoepfle.jpg
  - :interval: 300
    :desc: ch_birkli
    :url: http://www.birkli.ch/webcam/bildgross/aktuell_gross.jpg
    :coord:
      :lat: 45.866667
      :lon: 6.883333
    :use_in_timelapse: true
  - :interval: 300
    :desc: ischl
    :url: http://www.weti.net/cam/ischl.jpg
    :coord:
      :lat: 52.526248
      :lon: 13.361664
    :use_in_timelapse: true
  - :interval: 300
    :desc: hsb_broken
    :url: http://webcam.netco.de/bilder/hsb-brocken/brocken-bhf.jpg
  - :interval: 300
    :desc: italy_caorle
    :url: http://webcam.caorle.com/webcam-spiaggia-ponente/current.jpg
    :coord:
      :lat: 41.897676
      :lon: 12.495164
    :use_in_timelapse: true
  - :interval: 300
    :desc: italy_caorle_centro
    :url: http://webcam.caorle.com/webcam-centro-storico/current.jpg
    :coord:
      :lat: 41.897676
      :lon: 12.495164
    :use_in_timelapse: false
  - :interval: 300
    :desc: italy_lago
    :url: http://webcam.molveno.it/webcam/current_grande.jpg
  - :interval: 360
    :desc: cannobio
    :url: http://www.cannobio.net/resizeimgpiazza.asp?dimensioni=800
    :coord:
      :lat: 41.897676
      :lon: 12.495164
    :use_in_timelapse: true
  - :interval: 360
    :desc: villas_on_great_bay
    :url: http://www.thevillasongreatbay.com/images/netcam.jpg
    :coord:
      :lat: 18.069003
      :lon: -63.070621
    :use_in_timelapse: true
  - :interval: 320
    :desc: arolla_collonx
    :url: http://www.arolla.com/mt-collon/mtcollonx.jpg
    :resize: true
    :coord:
      :lat: 45.866667
      :lon: 6.883333
    :use_in_timelapse: true
  - :interval: 300
    :desc: arolla_widex
    :url: http://www.arolla.com/webcam_kurhaus/widex.jpg
    :resize: true
    :coord:
      :lat: 45.866667
      :lon: 6.883333
    :use_in_timelapse: true
  - :interval: 330
    :desc: bavaria_bergen
    :url: http://www.bayernwebcam.de/bilder/bergen.jpg
  - :interval: 300
    :desc: bavaria_marquartstein
    :url: http://www.bayernwebcam.de/bilder/marquartstein.jpg

# 2012-04-09
  - :interval: 330
    :desc: austria_schruns
    :url: http://schruns-tschagguns.at/kamera/kamera/aktuell.jpg
    :resize: false
    :coord:
      :lat: 47.080048
      :lon: 9.920596
    :use_in_timelapse: false

  - :interval: 300
    :desc: austria_tschagguns
    :url: http://webcams.salmhofer.at/webcam/tschagguns.jpg
    :resize: false
    :coord:
      :lat: 47.080008
      :lon: 9.901684
    :use_in_timelapse: false

  - :interval: 300
    :desc: austria_bezaus
    :url: http://www.hotelpostbezau.com/webcam/live/live.jpg
    :resize: false
    :coord:
      :lat: 47.385427
      :lon: 9.90251
    :use_in_timelapse: false

  - :interval: 300
    :desc: austria_schruns_ferienhotel
    :url: http://www.ferienhotel.at/kamera/kamera/aktuell.jpg
    :resize: false
    :coord:
      :lat: 47.385427
      :lon: 9.90251
    :use_in_timelapse: false

  - :interval: 300
    :desc: italy_liqueria_serra
    :url: http://www.meteolaserra.it/images/webcam/test/webcam2.php
    :resize: true
    :coord:
      :lat: 43.122804
      :lon: 13.232452
    :use_in_timelapse: false

  - :interval: 300
    :desc: italy_pfosl
    :url: http://zeppelinmedia.org/hotelpfoesl/webcam.jpg
    :resize: false
    :coord:
      :lat: 46.407371
      :lon: 11.44407
    :use_in_timelapse: false

  - :interval: 300
    :desc: tatry_chocholowska
    :url: http://kamery.topr.pl/chocholowska/chocholow.jpg
    :resize: false
    :coord:
      :lat: 49.221369
      :lon: 19.780973
    :use_in_timelapse: true

  - :interval: 300
    :desc: innsbruck_lans
    :url: http://live.tyrol.at/tyrolcams/lans/lans.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 300
    :desc: obertauern
    :url: http://www.snowwhite.at/obertauernwebcam/webcam01.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 300
    :desc: saalfelden_hotel_Ritzenhof1
    :url: http://www.ritzenhof.at/webcam/cam1/cam1.jpg
    :resize: true
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 300
    :desc: saalfelden_hotel_Ritzenhof2
    :url: http://www.ritzenhof.at/webcam/cam2/cam2.jpg
    :resize: true
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 300
    :desc: austria_gasthof_geierwallihof
    :url: http://geierwallihof.at/MOBOTIX/test.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 300
    :desc: chamonix_glace
    :url: http://www.compagniedumontblanc.fr/webcam/CMM1MERDEGLACE.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: chamonix_mont_blanc
    :url: http://www.webcams-stations.com/webcam/panoramique-massif-du-mont-blanc/vignette.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 300
    :desc: chamonix_valley
    :url: http://www.regione.vda.it/gestione/webcamgallery/showimage.aspx?nomefile=ferret.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 150
    :desc: mount_everest
    :url: http://www.evk2cnr.org/WebCams/PyramidOne/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: sheep_rock
    :url: http://www.nps.gov/webcams-joda/sheeprockcam.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false


#  - :interval: 300
#    :desc:
#    :url:
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false


# MOAR
# http://www.worldcam.pl/3,300,cat
