---
- :group: germany
  :array:
  - :interval: 120
    :desc: hahnenkoepfle
    :url: http://tramino.s3.amazonaws.com/s/das-hoechste/webcams/ifen-hahnenkoepfle.jpg

  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_kochelsee
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
#  - :interval: 120
#    :desc: germany_halle
#    :url: http://217.89.96.98/vhughsize.jpg
#    :coord:
#      :lat: 52.526248
#      :lon: 13.361664
#    :use_in_timelapse: true
  - :interval: 150
    :desc: germany_aussichtsteeg
    :url: http://www.breitenbergbahn.de/fileadmin/webcams/mobotix/steeg.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 150
    :desc: germany_aggensteinlift
    :url: http://www.breitenbergbahn.de/fileadmin/webcams/mobotix/aglstrecke.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 220
    :desc: de_mount1
    :url: http://cms.zugspitze.de/static/webcams/k02.jpg
  - :interval: 220
    :desc: de_mount2
    :url: http://cms.zugspitze.de/static/webcams/k04.jpg
    :coord:
      :lat: 45.866667
      :lon: 6.883333
    :use_in_timelapse: true
  - :interval: 180
    :desc: bavaria_bergen
    :url: http://www.bayernwebcam.de/bilder/bergen.jpg
#  - :interval: 180
#    :desc: bavaria_marquartstein
#    :url: http://www.bayernwebcam.de/bilder/marquartstein.jpg


  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/lienz/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_lienz
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/kronplatz/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_kronplatz
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/bruneck/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_bruneck
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/zellamsee/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_zellamsee
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false


  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/passthurn/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_passthurn
    :resize: true
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  # it has problems, but sometime works
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/badtoelz/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 600
    :desc: germany_badtoelz
    :resize: true
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/herzogstand/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_herzogstand
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/tegelberg/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_tegelberg
    :resize: true
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/gantkofel/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_gantkofel
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/meran/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_meran
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/innsbruck/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_innsbruck
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/funtenseetauern/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_funtenseetauern
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/jenner-ost/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_jenner_ost
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/hochries/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_hochries
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/pendling-ost/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_pendling_ost
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/pendling-west/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_pendling_west
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/wendelstein-ost/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_wendelstein_ost
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/wendelstein-west/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_wendelstein_west
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/sonnenbichl/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_sonnenbichl
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/karwendel/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_karwendel
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/meilerhuette/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_meilerhuette
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/arbersee/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_arbersee
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/arber-sued/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_arber_sued
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/arber-nord/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_arber_nord
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.panorama-blick.at/webcam/schwarzenbach/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_schwarzenbach
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.panorama-blick.at/webcam/flattach/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_flattach
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.megacam.at/webcam/amlach/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_amlach
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://foto.pensionweinberg.com/webcam/Raas/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_Raas
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.org/webcam/wallberg/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_wallberg
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.org/webcam/prasserbad/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_prasserbad
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.org/webcam/buchstein/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_buchstein
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :url_schema:
      :url_schema: "http://www.foto-webcam.com/webcam/Seekar/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_Seekar
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.com/webcam/BrauneckSpeichersee/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_BrauneckSpeichersee
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/BrauneckKarwendel/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_BrauneckKarwendel
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :url_schema:
      :url_schema: "http://www.asam-live.de/webcam/roedlass1/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_roedlass1
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.asam-live.de/webcam/amberg1/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_amberg1
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :url_schema:
      :url_schema: "http://www.asam-live.de/webcam/asamnet5/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_asamnet5
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.foto-webcam.com/webcam/hoefen/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_hoefen
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.panorama-blick.at/webcam/burgstalleralm/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_burgstalleralm
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.panorama-blick.at/webcam/wallackhaus/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_wallackhaus
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.panorama-blick.at/webcam/moertschach/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_moertschach
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.panorama-blick.at/webcam/lorenzalm/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_lorenzalm
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :url_schema:
      :url_schema: "http://www.panorama-blick.at/webcam/kleinfleisskees/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_kleinfleisskees
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.panorama-blick.at/webcam/gletscher-alteck/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_gletscher_alteck
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.panorama-blick.at/webcam/ankogel-sued/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_ankogel_sued
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      :url_schema: "http://www.panorama-blick.at/webcam/strohsack/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_strohsack
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/chavalatsch/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 1800 # every 30 minutes
      :time_offset: -3600
    :interval: 300
    :resize: true
    :desc: germany_chavalatsch
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false


#  - :url_schema:
#      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
#      :url_schema: "http://www.foto-webcam.eu/webcam/freimann/%Y/%m/%d/%H%M_la.jpg"
#      :time_modulo: 600 # every 10 minutes
#    :interval: 300
#    :desc: germany_freimann
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/muenchen/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_muenchen
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false


  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/grandsberg/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_grandsberg
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/norderney/%Y/%m/%d/%H%M_hu.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :resize: true
    :desc: germany_norderney
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

#  # too much storage for quality
#  - :interval: 120
#    :desc: germany_bergisch_gladbach
#    :url: http://bg01.onwebcam.net/aktuellesbild.aspx
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

  - :interval: 150
    :desc: germany_Diedenshausen
    :url: http://diedenshausen.de/assets/images/webcamddh.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: germany_trianel
    :url: http://212.37.52.98/record/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
    :resize: true

#  # bad quality
#  - :interval: 150
#    :desc: germany_odenwald
#    :url: http://www.odenwald.de/fileadmin/odenwald/Webcam/Marktplatz000M.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

  - :interval: 300
    :desc: germany_plauen
    :url: http://webcam-pl.tc-mw.de/cam3/img01.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: germany_walldurn1
    :url: http://www.wallduern.de/webcam/wallduern.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: germany_walldurn2
    :url: http://www.wallduern.de/webcam/hauptstr.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false








