---
- :group: germany
  :array:
  - :url_schema:
      :url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_kochelsee
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
#  - :interval: 120
#    :desc: germany_halle
#    :url: http://217.89.96.98/vhughsize.jpg
#    :coord:
#      :lat: 52.526248
#      :lon: 13.361664
#    :use_in_timelapse: true
  - :interval: 150
    :desc: germany_aussichtsteeg
    :url: http://www.breitenbergbahn.de/fileadmin/webcams/mobotix/steeg.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 150
    :desc: germany_aggensteinlift
    :url: http://www.breitenbergbahn.de/fileadmin/webcams/mobotix/aglstrecke.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 220
    :desc: de_mount1
    :url: http://cms.zugspitze.de/static/webcams/k02.jpg
  - :interval: 220
    :desc: de_mount2
    :url: http://cms.zugspitze.de/static/webcams/k04.jpg
    :coord:
      :lat: 45.866667
      :lon: 6.883333
    :use_in_timelapse: true
  - :interval: 180
    :desc: bavaria_bergen
    :url: http://www.bayernwebcam.de/bilder/bergen.jpg
#  - :interval: 180
#    :desc: bavaria_marquartstein
#    :url: http://www.bayernwebcam.de/bilder/marquartstein.jpg

- :group: france
  :array:
  - :interval: 180
    :desc: troyes
    :url: http://www.vision-environnement.com/webcams/Troyes2/image/webcam.jpg
  - :interval: 300
    :desc: chamonix_glace
    :url: http://www.compagniedumontblanc.fr/webcam/CMM1MERDEGLACE.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: chamonix_mont_blanc
    :url: http://www.webcams-stations.com/webcam/panoramique-massif-du-mont-blanc/vignette.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 300
    :desc: chamonix_valley
    :url: http://www.regione.vda.it/gestione/webcamgallery/showimage.aspx?nomefile=ferret.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
