- :group: greenland
  :array:
  - :resize: false
    :url: http://www.hotelarctic.com/files/webcam/webcamshot.jpg
    :interval: 180
    :desc: greenland_Ilulissat
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false