- :group: greece
  :array:
#  - :interval: 300
#    :desc: grecja_akropol
#    :url: http://cam.grandebretagneview.com/view_live1.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

# boring
#  - :interval: 120
#    :desc: grecja_ateny1
#    :url: http://nifada.com/webcam/current.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  # boring and huge
#  - :interval: 120
#    :desc: grecja_samarina
#    :url: http://www.snowreport.gr/snowcam/samarina/samarina.jpg
#    :resize: true
#    :jpg_quality_offset: -5
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false