- :group: iceland
  :array:
  - :resize: false
    :url: http://helgi.dk/webmyndir/image.jpg
    :interval: 180
    :desc: iceland_veidivotn
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false