---
- :group: italy
  :array:
#  - :interval: 360
#    :desc: italy_mount1
#    :url: http://www.ras.bz.it/img_webcams/scheibe/scheibe_P1.jpg
  - :interval: 300
    :desc: italy_caorle
    :url: http://webcam.caorle.com/webcam-spiaggia-ponente/current.jpg
    :coord:
      :lat: 41.897676
      :lon: 12.495164
    :use_in_timelapse: true
    :prior: 0
  - :interval: 120
    :desc: italy_caorle_centro
    :url: http://webcam.caorle.com/webcam-centro-storico/current.jpg
    :coord:
      :lat: 41.897676
      :lon: 12.495164
    :use_in_timelapse: false
  - :interval: 220
    :desc: italy_lago
    :url: http://webcam.molveno.it/webcam/current_grande.jpg
#  - :interval: 200
#    :desc: italy_liqueria_serra
#    :url: http://www.meteolaserra.it/images/webcam/test/webcam2.php
#    :resize: true
#    :coord:
#      :lat: 43.122804
#      :lon: 13.232452
#    :use_in_timelapse: false

  - :interval: 300
    :desc: italy_pfosl
    :url: http://zeppelinmedia.org/hotelpfoesl/webcam.jpg
    :resize: false
    :coord:
      :lat: 46.407371
      :lon: 11.44407
    :use_in_timelapse: false
