- :group: norway
  :array:
#  - :interval: 120
#    :desc: norway_birkeland
#    :url: http://www.torgrim.no/webcam.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

  - :interval: 300
    :desc: norway_pl_stac_polar1
    :url: http://www.hornsund.com/biblioteka/kamera/duze1.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: norway_pl_stac_polar2
    :url: http://www.hornsund.com/biblioteka/kamera/duze2.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

#  - :interval: 300
#    :desc: norway_tromso_aur
#    :url: http://polaris.nipr.ac.jp/~acaurora/aurora/Tromso/latest.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

  - :resize: false
    :url: http://linkativ.com/webcam/eidet000M.jpg
    :interval: 180
    :desc: norway_eidet
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

#  # static
#  - :url: http://ekstra.htg.no/webcam/img/tromso_fullsize.jpg
#    :interval: 300
#    :desc: no_tromso

  - :url: http://weather.cs.uit.no/wcam0_snapshots/wcam0_latest_medium.jpg
    :interval: 60
    :desc: no_tromso_univ
    :coord:
      #:lat: 70.085278
      # faked
      :lat: 45.085278
      :lon: 20.659444
    :use_in_timelapse: true
#  - :url: http://213.184.198.16/info/kamerabilder/k11/pos3.jpg
#    :interval: 300
#    :desc: norway_llesund_port1
  - :url: http://fevik.axiscam.net/axis-cgi/jpg/image.cgi?resolution=640x360
    :interval: 60
    :desc: norway_fevik
  - :url: http://www.alvdalmiv.no/images/stories/webkamera/images/stories/webkamera/steiabilde002.jpg
    :interval: 120
    :desc: norway_alvdal
#  - :url: http://www.flaamsbana.no/images/flaam_4.jpg
#    :interval: 300
#    :desc: norway_flaams

#  # static
#  - :url: http://ekstra.htg.no/webcam/img/harstad_fullsize.jpg
#    :interval: 300
#    :desc: norway_harstad
#    :coord:
#      #:lat: 70.085278
#      # faked
#      :lat: 45.085278
#      :lon: 20.659444
#    :use_in_timelapse: false

#  # static
#  - :url: http://ekstra.htg.no/webcam/img/alta_fullsize.jpg
#    :interval: 300
#    :desc: norway_alta

#  # static
#  - :url: http://www.hlk.no/webkamera/images//pos3.jpg
#    :interval: 300
#    :desc: norway_sama
#    :prior: -10

#  - :url: http://www.hlk.no/webkamera/images//pos2.jpg
#    :interval: 300
#    :desc: norway_hardstad2

#  # static
#  - :url: http://www.lofot-tidende.no/static/local/webcam/cubus.jpg
#    :interval: 600
#    :desc: norway_leknes
#    :prior: -5

#  # bad quality
#  - :url: http://home.online.no/~abjoernv/kamera/kam2.jpg
#    :interval: 300
#    :desc: norway_arne

#  - :url: http://home.custompublish.com/snsk/lyb_big.jpg
#    :interval: 150
#    :desc: norway_longyearbyen
#  - :resize: true
#    :url: http://www.svein-nordahl.com/01-gruvedalen.jpg
#    :interval: 300
#    :desc: norway_gruvedalen
#  - :url: http://www.promonorge.no/webcam/kamera.jpg
#    :interval: 220
#    :desc: norway_utsikt_s
  - :url: http://www.amihotel.no/webcamera/broadcast.jpg
    :interval: 150
    :desc: norway_tromso3
  - :url: http://www.arcticutleie.no/webkamera.jpg
    :interval: 120
    :desc: norwa_skjervoy
    :resize: true
    :jpg_quality_offset: -5
    :coord:
      #:lat: 70.085278
      # faked
      :lat: 45.085278
      :lon: 20.659444
    :use_in_timelapse: true

#  # static
#  - :url: http://ekstra.htg.no/webcam/img/sjovegan_fullsize.jpg
#    :interval: 180
#    :desc: norwa_sjovegan

# format changed
#  - :url: http://nordkapp.livecam360.com/cam3/php/show_lq_last.php
#    :interval: 450
#    :desc: norwa_north_cap
#  - :interval: 450
#    :desc: norway_lofoten
#    :url: http://www.lofoten-golf.no/webcam/Lgolf.jpg
#  - :interval: 150
#    :desc: norway_fjellet
#    :url: http://nktv.edbc.no/fjellet.jpg
  - :interval: 120
    :desc: norway_kabelvag
    :url: http://www.promonorge.no/webcam/kabelvag.jpg


