---
- :group: germany
  :array:
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/lienz/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_lienz
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/kronplatz/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_kronplatz
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/bruneck/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_bruneck
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/zellamsee/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_zellamsee
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false


  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/passthurn/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_passthurn
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/badtoelz/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_badtoelz
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/herzogstand/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_herzogstand
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/tegelberg/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_tegelberg
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/freimann/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_freimann
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/muenchen/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_muenchen
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false


  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/grandsberg/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_grandsberg
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :url_schema:
      #:url_schema: "http://www.foto-webcam.eu/webcam/kochelsee/%Y/%m/%d/%H%M_la.jpg"
      :url_schema: "http://www.foto-webcam.eu/webcam/norderney/%Y/%m/%d/%H%M_la.jpg"
      :time_modulo: 600 # every 10 minutes
    :interval: 300
    :desc: germany_norderney
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
