- :group: poland
  :array:
  - :resize: false
    :url: http://www.kamera.karpacz.pl/lodowiec.jpg
    :interval: 120
    :desc: karpacz_garb
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false


- :group: slovakia
  :array:
  - :resize: false
    :url: http://www.sirokebase.sk/meteo/sirokebase000M.jpg
    :interval: 120
    :desc: slovakia_siroke
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

- :group: chech
  :array:
  - :resize: false
    :url: http://www.tanvald.cz/data/webkamery/tanvald.jpg
    :interval: 120
    :desc: chech_tanvald
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://www.chalupanarozcesti.cz/webcam/video.jpg
    :interval: 120
    :desc: chech_chalupanarozcesti
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://kamery.humlnet.cz/images/webcams/pecpodsnezkou/1024x768.jpg
    :interval: 120
    :desc: chech_pecpodsnezkou
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://kamery.humlnet.cz/images/webcams/gablenz2/1024x768.jpg
    :interval: 120
    :desc: chech_trutnov2
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://kamery.humlnet.cz/images/webcams/litomerice/1024x768.jpg
    :interval: 120
    :desc: chech_litomerice
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://kamery.humlnet.cz/images/webcams/lovos/1024x768.jpg
    :interval: 120
    :desc: chech_lovos
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://http://kamery.humlnet.cz/images/webcams/cerna_hora/1024x768.jpg
    :interval: 120
    :desc: chech_cerna_hora
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://kamery.humlnet.cz/images/webcams/labska_bouda/1024x768.jpg
    :interval: 120
    :desc: chech_labska_bouda
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://kamery.humlnet.cz/images/webcams/boudapodsnezkou/1024x768.jpg
    :interval: 120
    :desc: chech_boudapodsnezkou
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://kamery.humlnet.cz/images/webcams/prkenak/1024x768.jpg
    :interval: 120
    :desc: chech_prkenak
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://kamery.humlnet.cz/images/webcams/boruvka/1024x768.jpg
    :interval: 120
    :desc: chech_velka_upa_boruvka
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

- :group: sweden
  :array:
  - :resize: false
    :url: http://uk.jokkmokk.jp/photo/nr4/latest.jpg
    :interval: 180
    :desc: sweden_porjus
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

- :group: norway
  :array:
  - :resize: false
    :url: http://linkativ.com/webcam/eidet000M.jpg
    :interval: 180
    :desc: norway_eidet
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

- :group: iceland
  :array:
  - :resize: false
    :url: http://helgi.dk/webmyndir/image.jpg
    :interval: 180
    :desc: iceland_veidivotn
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

- :group: greenland
  :array:
  - :resize: false
    :url: http://www.hotelarctic.com/files/webcam/webcamshot.jpg
    :interval: 180
    :desc: greenland_Ilulissat
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

- :group: canada
  :array:
  - :resize: false
    :url: http://www.kimmirutweather.com/webcam.jpg
    :interval: 180
    :desc: canada_kimmirut
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

- :group: usa
  :array:
  - :resize: false
    :url: http://feeder.gina.alaska.edu/webcam-uaf-barrow-seaice-images/current/image
    :interval: 180
    :desc: usa_barrow
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://www.skimarmot.com/webcams/MOBOTIX/upper.jpg
    :interval: 180
    :desc: usa_mobotix_upper
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false


- :group: finland
  :array:
  - :resize: false
    :url: http://alk.tiehallinto.fi/alk/kelikamerat/C1453501041645.jpg
    :interval: 180
    :desc: finland_KILPISJA
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://www.otosservice.net/getimage.php?server=localhost&cam_id=00408C850CEE&uniq=1
    :interval: 180
    :desc: finland_Latukamera
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://alk.tiehallinto.fi/alk/kelikamerat/C1452401041645.jpg
    :interval: 180
    :desc: finland_Peltovu
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://alk.tiehallinto.fi/alk/kelikamerat/C1453507041655.jpg
    :interval: 180
    :desc: finland_ENONTEKIO
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://alk.tiehallinto.fi/alk/kelikamerat/C1451201041658.jpg
    :interval: 180
    :desc: finland_ROPINSALMI
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://alk.tiehallinto.fi/alk/kelikamerat/C1453301041654.jpg
    :interval: 180
    :desc: finland_Utsjoki
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false
  - :resize: false
    :url: http://alk.tiehallinto.fi/alk/kelikamerat/C1454001041654.jpg
    :interval: 180
    :desc: finland_SODANKYLA
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

