---
- :group: andorra
  :array:
  - :url: http://www.bagn.obs-mip.fr/webcamV2/webcam85.jpg
    :interval: 160
    :desc: andorra_pic_du_mudi
    :coord:
      :lat:
      :lon:
    :use_in_timelapse: false

  - :url: http://www.altiservice.com/webcams/FRP2000/fontromeu.jpg
    :interval: 80
    :desc: andorra_font_romeu
    :coord:
      :lat:
      :lon:
    :use_in_timelapse: false

- :group: austria
  :array:
  - :interval: 300
    :desc: austria_bad_gastein
    :url_schema:
      :url_schema: "http://panodata1.panomax.at/cams/23/%Y/%m/%d//%H-%M-00_default.jpg"
      :time_modulo: 600 # every 20 minutes
      :time_offset: 0 # 12 minutes
    :resize: false
    :coord:
      :lat:
      :lon:
    :use_in_timelapse: false

  - :interval: 120
    :desc: austria_elbigenalp
    :url: http://www.hotel-post.biz/typo/tl_files/webcam/camera.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 120
    :desc: austria_Kufstein_Unterer_Stadtplatz
    :url: http://www.webcam.kufnet.at/livebild/untererstadtplatz/image.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 120
    :desc: austria_Festungsarena_Unterer_Stadtplatz
    :url: http://www.webcam.kufnet.at/livebild/festungsarena/image.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 90
    :desc: austria_Kufsteinblick
    :url: http://www.webcam.kufnet.at/livebild/kufsteinblick/image.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 180
    :desc: austria_lienz
    :url: http://www.hochsteinhuette.at/images/stories/webcam/livebild.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 180
    :desc: austria_loser1
    :url: http://www.mentalworks.com/live/altaussee.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: austria_loser3
    :url: http://www.mentalworks.com/live/loser.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: austria_Luckneralm
    :url: http://www.lucknerhuette.at/webcam/lucknerhuette.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: austria_Neue_Regensburger
    :url: http://www.regensburgerhuette.at/fileadmin/webcam/html/fileadmin/IPCamera/snapshot-wz.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

- :group: check
  :array:
  - :interval: 300
    :desc: czech_kravare
    :url: http://new.kravarecl.cz/kamera/webcam.html
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

- :group: estonia
  :array:
  - :interval: 120
    :desc: estonia_tartu
    :url: http://meteo.physic.ut.ee/webcam/praegu/big.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

- :group: finland
  :array:
  - :interval: 90
    :desc: finland_Kemijarvi
    :url: http://www.koillislapinsahko.fi/webcam/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 100
    :desc: finland_levi
    :url: http://213.28.111.31/record/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: finland_posio
    :url: http://posiokamera.fns.fi/kuvat/kuva.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

- :group: france
  :array:
  - :interval: 300
    :desc: france_alpes_village_1
    :url: http://www.webcam-hd.com/Images/2alpes-ot_village/pano/2alpes-ot_village1.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: france_alpes_village_2
    :url: http://www.webcam-hd.com/Images/2alpes-ot_village/pano/2alpes-ot_village2.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: france_alpes_village_3
    :url: http://www.webcam-hd.com/Images/2alpes-ot_village/pano/2alpes-ot_village3.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: france_alpes_village_4
    :url: http://www.webcam-hd.com/Images/2alpes-ot_village/pano/2alpes-ot_village4.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: france_alpes_village_5
    :url: http://www.webcam-hd.com/Images/2alpes-ot_village/pano/2alpes-ot_village5.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: france_alpes_village_6
    :url: http://www.webcam-hd.com/Images/2alpes-ot_village/pano/2alpes-ot_village6.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: france_alpes_village_7
    :url: http://www.webcam-hd.com/Images/2alpes-ot_village/pano/2alpes-ot_village7.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 600
    :desc: france_orcieres
    :url: http://www.trinum.com/ibox/ftpcam/mega_orcieres-croze.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

- :group: greece
  :array:
  - :interval: 300
    :desc: grecja_akropol
    :url: http://cam.grandebretagneview.com/view_live1.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 120
    :desc: grecja_ateny1
    :url: http://nifada.com/webcam/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 120
    :desc: grecja_samarina
    :url: http://www.snowreport.gr/snowcam/samarina/samarina.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

- :group: spain
  :array:
  - :interval: 300
    :desc: hiszpania_picos_de_europe
    :url: http://www.colladojermoso.com/www/mobotix/picosdeeuropa.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

- :group: liechtenstein
  :array:
  - :interval: 120
    :desc: liechte_steg
    :url: http://video.lkw.li/liveCamSteg/lkw-stausee-steg.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

- :group: germany
  :array:
  - :interval: 120
    :desc: germany_bergisch_gladbach
    :url: http://bg01.onwebcam.net/aktuellesbild.aspx
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 150
    :desc: germany_Diedenshausen
    :url: http://diedenshausen.de/assets/images/webcamddh.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 150
    :desc: germany_trianel
    :url: http://212.37.52.98/record/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
    :resize: true

  - :interval: 150
    :desc: germany_odenwald
    :url: http://www.odenwald.de/fileadmin/odenwald/Webcam/Marktplatz000M.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: germany_plauen
    :url: http://webcam-pl.tc-mw.de/cam3/img01.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 150
    :desc: germany_walldurn1
    :url: http://www.wallduern.de/webcam/wallduern.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 120
    :desc: germany_walldurn2
    :url: http://www.wallduern.de/webcam/hauptstr.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

- :group: norway
  :array:
  - :interval: 120
    :desc: norway_birkeland
    :url: http://www.torgrim.no/webcam.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: norway_pl_stac_polar1
    :url: http://www.hornsund.com/biblioteka/kamera/duze1.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: norway_pl_stac_polar2
    :url: http://www.hornsund.com/biblioteka/kamera/duze2.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: norway_tromso_aur
    :url: http://polaris.nipr.ac.jp/~acaurora/aurora/Tromso/latest.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 90
    :desc: switzerland_costa_borgnome
    :url: http://www.costa-borgnone.ch/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 120
    :desc: switzerland_charmey
    :url: http://fribourg.cam.stpartner.ch/cam/charmey/camera2/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 120
    :desc: switzerland_lauerz
    :url: http://lauerz.ch.web1.init0hosting.net/webcam/cam_lauerz-hasen.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 90
    :desc: switzerland_martigny
    :url: http://213.221.142.195:8888/record/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 120
    :desc: switzerland_ronco
    :url: http://www.webcamticino.ch/vivereblu/gallery/img/webcam/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 100
    :desc: switzerland_soglio
    :url: http://www.webcam.valtline.it/soglio.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: switzerland_susten
    :url: http://www.bella-tola.ch/fileadmin/images/webcam.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 90
    :desc: switzerland_veysonnaz
    :url: http://www.caboulis.ch/sion.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 90
    :desc: switzerland_zermatt_kirche
    :url: http://www.zermatt.ch/html/bergbahnen/webcams/kirche.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 120
    :desc: switzerland_zermatt_bahnhof
    :url: http://www.zermatt.ch/html/bergbahnen/webcams/bahnhof.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: switzerland_zermatt_matterhorn
    :url: http://www.zermatt.ch/html/bergbahnen/webcams/matterhorn2.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 200
    :desc: switzerland_zermatt_ober
    :url: http://www.schonegg.ch/webcam.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
