---
- :group: poland
  :array:

  - :resize: false
    :url: http://www.ztikm.szczecin.pl/kamera/live/view.jpg
    :interval: 180
    :desc: poland_debki
    :use_in_timelapse: false

#  # boring
#  - :interval: 120
#    :desc: belchatow_plac_narutowicza
#    :url: http://81.15.194.42:8080/cam_9.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  # boring
#  - :interval: 180
#    :desc: belchatow_hala_energia
#    :url: http://81.15.194.42:8080/cam_2.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  - :interval: 300
#    :desc: bielsko_biala_aeroklub
#    :url: http://pogodynka.pl/http/assets/products/pogodynka/webcam/bielskobiala/bielskobiala.php.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :interval: 120
#    :desc: bielsko_biala_elektrocieplownia1
#    :url: http://www.pke.pl/kamery/zec/cam_bb_1000M.jpg
#    :resize: true
#    :jpg_quality_offset: -2
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :interval: 120
#    :desc: bielsko_biala_elektrocieplownia2
#    :url: http://www.pke.pl/kamery/zec/cam_bb_2000M.jpg
#    :resize: true
#    :jpg_quality_offset: -2
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  # huge
#  - :interval: 150
#    :desc: boleslawiec_rynek
#    :url: http://webcam.istotne.pl/rynek000M.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  - :interval: 300
#    :desc: bystrzyca_klodzka_spalona
#    :url: http://wcam.pl/~ozmo/kamera.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
  - :interval: 150
    :desc: cedry_wielkie_marina1
    :url: http://79.190.93.34:81/cgi-bin/encoder?USER=www&PWD=www&SNAPSHOT
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

#  # huge
#  - :interval: 150
#    :desc: cedry_wielkie_marina2
#    :url: http://79.190.93.34:82/cgi-bin/encoder?USER=www&PWD=www&SNAPSHOT
#    :resize: true
#    :jpg_quality_offset: -3
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  - :interval: 150
#    :desc: nowy_sacz_rynek
#    :url: http://www.nowysacz.pl/execute.php?nav=535&mod=live&q=image
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  # fail
#  - :interval: 150
#    :desc: jaworzno_elektrownia1
#    :url: http://www.pke.pl/kamery/ej3/cam1_ej3_bio_les.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  # bad quality, boring
#  - :interval: 180
#    :desc: jelenia_gora_pano
#    :url: http://www.media-art24.com/kamery/jeleniagora.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false


#  - :interval: 90
#    :desc: katowice_dworzec
#    :url: http://www.ett.net.pl/video.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :interval: 600
#    :desc: korbielow_pilsko1
#    :url: http://cypisek.korbielow.net/webcam1/cam1_17.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :interval: 600
#    :desc: korbielow_pilsko2
#    :url: http://cypisek.korbielow.net/webcam2/cam2_17.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false


#  # bad quality
#  - :interval: 300
#    :desc: krosno
#    :url: http://pogodynka.pl/http/assets/products/pogodynka/webcam/krosno/krosno.php.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#    :prior: -10

#  - :interval: 150
#    :desc: parafia_klemensa
#    :url: http://178.218.224.7/kam/10image2.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
  - :interval: 150
    :desc: male_ciche
    :url: http://www.maleciche.home.pl/kamery/ikonoskop.php?o=kamera3000M.jpg&s=800&w=600
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
#  - :interval: 200
#    :desc: lubomierz
#    :url: http://www.lubomierz.com/kam_01.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :interval: 120
#    :desc: muszyna_lewiatan
#    :url: http://www.kamera.muszyna.info.pl/lewiatan_000M.jpg
#    :resize: true
#    :jpg_quality_offset: -12
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :interval: 120
#    :desc: muszyna_tatry
#    :url: http://www.kamera.muszyna.info.pl/kamera2/m_tatry_000M.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  # boring
#  - :interval: 300
#    :desc: niedzica_polana_sosny
#    :url: http://www.niedzica.pl/uploads/webcam/niedzica8000M.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  - :interval: 120
#    :desc: grodek_nad_dunajcem
#    :url: http://83.0.153.236/jpg/image.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
  - :interval: 150
    :desc: ski_park_magura
    :url: http://skisun.pl/kamery/mag3/image.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false
  - :interval: 300
    :desc: jezioro_nyskie
    :url: http://www.nor.nysa.pl/cam/nor001M.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

#  # boring
#  - :interval: 165
#    :desc: osiek
#    :url: http://www.osieknet.pl/kamerka.php?k=2
#    :resize: true
#    :jpg_quality_offset: -10
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  - :interval: 300
#    :desc: koninki_8
#    :url: http://timeforu.home.pl/ftp/koninki/8.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :interval: 300
#    :desc: koninki_9
#    :url: http://timeforu.home.pl/ftp/koninki/9.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  - :interval: 300
#    :desc: koninki_10
#    :url: http://timeforu.home.pl/ftp/koninki/10.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  - :interval: 200
#    :desc: szczeliniec_z_radkowa
#    :url: http://bastech.com.pl/radkow/widok.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  # static
#  - :interval: 200
#    :desc: miedzygorze
#    :url: http://www.miedzygorze.com.pl/kamera.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  - :interval: 150
#    :desc: jaworki_homole
#    :url: http://www.arenanarciarska.pl/kam/000M.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :interval: 300
#    :desc: kasprowy_giewont
#    :url: http://www.pkl.pl/kamera/Gor001M.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#
#  - :interval: 450
#    :desc: plaza_stogi
#    :url: http://www.plazastogi.pl/kamera/00B800014FF7%28002enqe%29_0_20121128002601_202174.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

#  # boring, bad quality
#  - :interval: 300
#    :desc: kalety_centrum
#    :url: http://kamera01.kalety.net/LATEST.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

  - :interval: 120
    :desc: elektrownia_zielony_blok
    :url: http://193.16.229.11/live/image0.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :url: http://www.zakopaneonline.eu/webcam/zakopane.jpg
    :pre_url: http://www.zol.pl/webcam/
    :referer: http://www.zol.pl/webcam/
    :interval: 180
    :desc: zakopane
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
  - :url: http://www.zakopaneonline.eu/webcam2/zakopane.jpg
    :pre_url: http://www.zol.pl/webcam/
    :referer: http://www.zol.pl/webcam/
    :interval: 180
    :desc: zakopane2
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
  - :url: http://www.zakopaneonline.eu/webcam3/zakopane.jpg
    :pre_url: http://www.zol.pl/webcam/
    :referer: http://www.zol.pl/webcam/
    :interval: 180
    :desc: zakopane3
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
  - :url: http://kamery.topr.pl/moko/moko_01.jpg
    :interval: 240
    :desc: moko
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
  - :url: http://kamery.topr.pl/goryczkowa/gorycz.jpg
    :interval: 210
    :desc: goryczkowa
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
  - :url: http://kamery.topr.pl/moko_TPN/moko_02.jpg
    :interval: 210
    :desc: moko2
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
  - :url: http://kamery.topr.pl/stawy1/stawy1.jpg
    :interval: 180
    :desc: stawy
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true

  - :url: http://kamery.topr.pl/stawy2/stawy2.jpg
    :interval: 180
    :desc: stawy2
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true

  - :url: http://kamery.topr.pl/gasienicowa/gasie.jpg
    :interval: 180
    :desc: gasienicowa
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
  - :url: http://www.zakopaneonline.eu/webcam6/koscielisko.jpg
    :referer: http://www.zol.pl/webcam/
    :interval: 180
    :desc: koscielisko
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
  - :url: http://www.zakopaneonline.eu/webcam9/krupowki.jpg
    :referer: http://www.zol.pl/webcam/
    :interval: 300
    :desc: krupowki
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
  - :url: http://www.zakopaneonline.eu/webcam8/zakopianka.jpg
    :referer: http://www.zol.pl/webcam/
    :interval: 180
    :desc: zakopianka
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
#  - :url: http://www.kamera.zadzial.pl/cam_1.jpg
#    :interval: 180
#    :desc: beskid1
#  - :url: http://www.zakopaneonline.eu/webcam4/bukowina.jpg
#    :referer: http://www.zol.pl/webcam/
#    :interval: 300
#    :desc: bukowina
#    :coord:
#      :lat: 49.304778
#      :lon: 19.916832
#    :use_in_timelapse: false
  - :url: http://www.zakopaneonline.eu/webcams/kubik.jpg
    :referer: http://www.zol.pl/webcam/
    :interval: 180
    :desc: willa_kubik
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
  - :url: http://z-ne.pl/kamery/giewont_zakopane.jpg
    :interval: 120
    :desc: giewont_zakopane
    :resize: true
    :jpg_quality_offset: -3
    :coord:
      :lat: 49.304778
      :lon: 19.916832
    :use_in_timelapse: true
#  - :url: http://www.pkl.pl/kamera/kasprowy_gorna_stacja_na_gasienicowa.jpg
#    :interval: 220
#    :desc: tatry_kasprowy_gasienicowa
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
  - :url: http://www.zakopaneonline.eu/webcam7/murzasichle.jpg
    :referer: http://www.zol.pl/webcam/
    :interval: 180
    :desc: tatry_murzasichle
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

#  # static
#  - :url: http://www.tatrzanskie-turnie.pl/kamera/video.jpg
#    :interval: 180
#    :desc: tatry_tatrz_turnie
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false

  - :interval: 200
    :desc: tatry_chocholowska
    :url: http://kamery.topr.pl/chocholowska/chocholow.jpg
    :resize: false
    :coord:
      :lat: 49.221369
      :lon: 19.780973
    :use_in_timelapse: true


  - :resize: false
    :url: http://www.niedzica.pl/uploads/webcam/niedzica2.jpg
    :interval: 150
    :desc: pieniny_niedzica2_polana_sosny
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

  - :url: http://www.pieninyportal.com/images/stories/webcamera/pieninyportal.jpg
    :interval: 120
    :desc: trzy_korony
#  - :url: http://www.kamery.szczawnica.pl/foto5000M.jpg
#    :interval: 220
#    :desc: pieniny_szczawnica
#    :coord:
#      :lat: 49.422778
#      :lon: 20.482778
#    :use_in_timelapse: false
#  - :url: http://www.kamery.szczawnica.pl/foto7000M.jpg
#    :interval: 180
#    :desc: pieniny_przystan_flisacka
#    :coord:
#      :lat: 49.422778
#      :lon: 20.482778
#    :use_in_timelapse: false
#  - :url: http://www.kamery.szczawnica.pl/foto4.jpg
#    :interval: 210
#    :desc: pieniny_gory
#    :coord:
#      :lat: 49.422778
#      :lon: 20.482778
#    :use_in_timelapse: false
  - :url: http://www.niedzica.pl/uploads/webcam/niedzica7000M.jpg
    :interval: 240
    :desc: pieniny_niedzica
    :coord:
      :lat: 49.422778
      :lon: 20.482778
    :use_in_timelapse: false
#  - :url: http://www.kroscienko-nad-dunajcem.pl/kamera/widok1.jpg
#    :interval: 150
#    :desc: pieniny_most_kroscienko
#    :coord:
#      :lat: 49.422778
#      :lon: 20.482778
#    :use_in_timelapse: false
#  - :url: http://www.pieninyportal.com/images/stories/webcamera/pieninyportal-haligovce.jpg
#    :interval: 240
#    :desc: pieniny_haligovce
#    :coord:
#      :lat: 49.422778
#      :lon: 20.482778
#    :use_in_timelapse: false
  - :url: http://www.ugazdy.pl/kamerka/obrazek.jpg
    :interval: 180
    :desc: gorce_u_gazdy
    :coord:
      :lat: 50.9
      :lon: 15.333333
    :use_in_timelapse: false
#  - :url: http://www.fastcom.net.pl/zdjecia-kamera/zdjecie.php
#    :interval: 210
#    :desc: szczyrk_skrzyczne1
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :url: http://www.fastcom.net.pl/zdjecia-kamera/zdjecie2.php
#    :interval: 220
#    :desc: szczyrk_beskidek
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false
#  - :url: http://www.niedzica.pl/uploads/webcam/niedzica6.jpg
#    :interval: 120
#    :desc: niedzica
#  - :url: http://cedr.irsm.cas.cz/rinex/meteo/webcam_photo.php?station=bisk
#    :interval: 120
#    :desc: bisk
#  - :url: http://cedr.irsm.cas.cz/rinex/meteo/webcam_photo.php?station=bisk2
#    :interval: 120
#    :desc: bisk2
#  - :url: http://cedr.irsm.cas.cz/rinex/meteo/webcam_photo.php?station=bisk3
#    :interval: 120
#    :desc: bisk3
#  - :url: http://cedr.irsm.cas.cz/rinex/meteo/webcam_photo.php?station=bisk4
#    :interval: 120
#    :desc: bisk4




#  # fail
#  # http://www.kamerybieszczady.czaszyn.pl/
#  - :url: http://obsluga-medialna.pl/kamera/kamera_wetlina/index.php
#    :interval: 150
#    :desc: bieszczady_wetlina
#    :coord:
#      :lat: 49.1575
#      :lon: 22.467222
#    :use_in_timelapse: false

  - :url: http://obsluga-medialna.pl/kamera/czaszyn/index_cz.php
    :interval: 110
    :desc: bieszczady_czaszyn
    :coord:
      :lat: 49.1575
      :lon: 22.467222
    :use_in_timelapse: false
  - :url: http://ewymiar.pl/czaszyn/jpg/1.jpg
    :interval: 120
    :desc: bieszczady_czaszyn2
    :coord:
      :lat: 49.1575
      :lon: 22.467222
    :use_in_timelapse: false
  - :url: http://www.flisacy.pl/kamera1/webcam1.jpg
    :interval: 120
    :desc: pieniny_fliska
    :use_in_timelapse: false
  - :url: http://www.polskielng.pl/fileadmin/pliki/kamera_plng/limg1.jpg
    :interval: 180
    :desc: swinoujscie_terminal_gaz
    :use_in_timelapse: false
  - :url: http://k.nocowanie.pl/ustroniem/kamera1/obraz_aktualny.jpg
    :interval: 180
    :desc: ustronie_morskie
    :use_in_timelapse: false
#  - :url: http://esolina.pl/kamera/widok.php
#    :interval: 120
#    :desc: bieszczady_polanczyk
#    :coord:
#      :lat: 49.1575
#      :lon: 22.467222
#    :use_in_timelapse: false

#  # bad quality
#  - :url: http://images.webcams.travel/webcam/1309464984.jpg
#    :interval: 180
#    :desc: bieszczady_u_gorne
#    :coord:
#      :lat: 49.1575
#      :lon: 22.467222
#    :use_in_timelapse: false

  - :url: http://images.webcams.travel/webcam/1287047915.jpg
    :interval: 300
    :desc: bieszczady_przyslup_carynski
    :coord:
      :lat: 49.1575
      :lon: 22.467222
    :use_in_timelapse: false
  - :url: http://images.webcams.travel/webcam/1248008562.jpg
    :interval: 240
    :desc: bieszczady_lesko_centrum
    :coord:
      :lat: 49.1575
      :lon: 22.467222
    :use_in_timelapse: false

#  # not enough good quality
#  - :url: http://83.18.111.249:8080/cgi-bin/viewer/video.jpg
#    :interval: 90
#    :desc: bieszczady_keja_siarkopol
#    :coord:
#      :lat: 49.1575
#      :lon: 22.467222
#    :use_in_timelapse: false


  - :resize: true
    :jpg_quality_offset: 10
    :url: http://www.dalekieobserwacje.eu/wp-content/uploads/webcam_skrzyczne/A-hi.jpg
    :interval: 240
    :desc: skrzyczne
    :coord:
      :lat: 49.684444
      :lon: 19.030278
    :use_in_timelapse: false
  - :resize: true
    :jpg_quality_offset: 10
    :url: http://www.dalekieobserwacje.eu/wp-content/uploads/webcam_szyndzielnia/A-hi.jpg
    :interval: 240
    :desc: szyndzielnia
    :coord:
      :lat: 49.753111
      :lon: 18.999667
    :use_in_timelapse: false
  - :resize: true
    :jpg_quality_offset: 10
    :url: http://www.dalekieobserwacje.eu/wp-content/uploads/webcam_rysianka/A-hi.jpg
    :interval: 240
    :desc: rysianka
    :coord:
      :lat: 49.536111
      :lon: 19.234444
    :use_in_timelapse: false
  - :resize: true
    :jpg_quality_offset: 10
    :url: http://www.dalekieobserwacje.eu/wp-content/uploads/webcam_liwocz/A-hi.jpg
    :interval: 240
    :desc: liwocz
    :coord:
      :lat: 49.813211
      :lon: 21.351397
    :use_in_timelapse: false
  - :resize: true
    :jpg_quality_offset: 10
    :url: http://www.dalekieobserwacje.eu/wp-content/uploads/webcam_widnica/A-hi.jpg
    :interval: 240
    :desc: widnica
    :coord:
      :lat: 50.399167
      :lon: 20.031389
    :use_in_timelapse: false
  - :resize: true
    :jpg_quality_offset: 10
    :url: http://www.dalekieobserwacje.eu/wp-content/uploads/webcam_mikolow/A-hi.jpg
    :interval: 240
    :desc: mikolow
    :coord:
      :lat: 50.166667
      :lon: 18.9
    :use_in_timelapse: false


