- :group: spain
  :array:
  - :url: http://www.bagn.obs-mip.fr/webcamV2/webcam85.jpg
    :interval: 160
    :desc: andorra_pic_du_mudi
    :coord:
      :lat:
      :lon:
    :use_in_timelapse: false

#  - :interval: 300
#    :desc: hiszpania_picos_de_europe
#    :url: http://www.colladojermoso.com/www/mobotix/picosdeeuropa.jpg
#    :resize: false
#    :coord:
#      :lat: 0.0
#      :lon: 0.0
#    :use_in_timelapse: false