- :group: sweden
  :array:
  - :resize: false
    :url: http://uk.jokkmokk.jp/photo/nr4/latest.jpg
    :interval: 180
    :desc: sweden_porjus
    :coord:
      :lat: 50.288333
      :lon: 18.973611
    :use_in_timelapse: false

  - :resize: false
    :url: http://www.liveevent.se/webbkamera/tv4/goteborg/tv4_goteborg_1_1280.jpg
    :interval: 200
    :desc: sweden_goteborg
    :resize: true
    :jpg_quality_offset: -5
  - :url: http://www.gehammar.se/not001.jpg
    :interval: 200
    :desc: sweden_hjalmo
  - :resize: false
    :jpg_quality_offset: 4
    :url: http://www.liveevent.se/webbkamera/ca-kalmar/ca_kalmar_1_1280.jpg
    :interval: 180
    :desc: sweden_kalmar
#  - :resize: true
#    :jpg_quality_offset: -8
#    :url: http://www.venjan.se/cam/kupan_cam.jpg
#    :interval: 200
#    :desc: sweden_kupan
#    :prior: -8
#  - :resize: true
#    :url: http://livecam.mora.se/imageb.jpg
#    :interval: 240
#    :desc: sweden_vosalo
#  - :resize: true
#    :url: http://87.237.210.145/~checkpoi/webcam/klappen/webcam_10_1280.jpg
#    :interval: 450
#    :desc: sweden_klappen
# low space, not so interesting
#  - :resize: true
#    :jpg_quality_offset: -2
#    :url: http://www.hamrafjallet.se/kamera/webbkamror/topmega.jpg
#    :interval: 150
#    :desc: sweden_tandallen

#  - :resize: true
#    :url: http://www.liveevent.se/webbkamera/tv4/sundsvall/tv4_sundsvall_1_1280.jpg
#    :interval: 300
#    :desc: sweden_tvn4

  - :resize: false
    :jpg_quality_offset: 4
    :url: http://dedi68.aname.net/~checkpoi/webcam/unostorn/webcam_6_1280.jpg
    :interval: 180
    :desc: sweden_unostorm
  - :resize: false
    :jpg_quality_offset: 4
    :url: http://87.237.210.145/~checkpoi/webcam/visby_stora_torget/webcam_10_1280.jpg
    :interval: 120
    :desc: swedeb_visby
    :coord:
      # faked
      :lat: 45.085278
      :lon: 20.659444
    :use_in_timelapse: true

