---
- :group: world
  :array:
  - :url: http://www.monopol-andermatt.ch/cam/webcam.jpg
    :interval: 220
    :desc: switz_andermatt
  - :url: http://www.appenzell-ai.ch/appenzell_fotoold.jpg
    :interval: 220
    :desc: switz_appenzell
  - :url: http://www.obergoms.ch/tourismus/service/webcams/obergesteln.php?e_12_14_getimage=1
    :interval: 220
    :desc: switz_obergoms
  - :url: http://webcam.21.by/pub/webcam/148/size_0.jpg
