---
- :group: world
  :array:
  - :interval: 150
    :desc: mount_everest
    :url: http://www.evk2cnr.org/WebCams/PyramidOne/current.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

  - :interval: 300
    :desc: sheep_rock
    :url: http://www.nps.gov/webcams-joda/sheeprockcam.jpg
    :resize: false
    :coord:
      :lat: 0.0
      :lon: 0.0
    :use_in_timelapse: false

#  - :url: http://crest.ernet.in/webcam/images/latest.jpg
#    :interval: 300
#    :desc: himalayan_chandra
